plugins:
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-rake
  - rubocop-rspec
  - rubocop-md

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Max: 65
  Exclude:
    - 'keep_alive.gemspec'
    - 'spec/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 155

Metrics/MethodLength:
  Max: 65

Metrics/AbcSize:
  Max: 90

Metrics/CyclomaticComplexity:
  Max: 24

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ClassLength:
  Max: 350


RSpec/ExampleLength:
  Max: 25

RSpec/NestedGroups:
  Max: 5

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 7
